# ======================================================================
# Auth Microservice
# Loads configuration from Config Server and registers with Eureka
# ======================================================================

spring:
  application:
    name: auth-service

  config:
    import: optional:configserver:http://localhost:9090

  datasource:
    url: jdbc:postgresql://localhost:5432/ms_auth_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  cloud:
    config:
      retry:
        max-attempts: 6
        initial-interval: 1000
        multiplier: 1.5
        max-interval: 10000

server:
  port: 8082

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    com.ecommerce.auth: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh
  endpoint:
    health:
      show-details: always

example:
  app:
    jwtSecret: "mySuperSecretKeyForJwtAccessTokenGeneration123456"
    jwtRefreshSecret: "mySuperSecretKeyForJwtRefreshTokenGeneration654321"
    jwtExpirationMs: 3600000            # 1 hour
    jwtRefreshExpirationMs: 604800000   # 7 days

springdoc:
  api-docs:
    path: /api/docs

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    should-unregister-on-shutdown: false