# ===============================================================
# DISCOVERY SERVICE (Eureka Server)
# Handles service registration and discovery for microservices
# ===============================================================

server:
  port: 8761  # Port for Eureka dashboard (http://localhost:8761)

spring:
  application:
    name: discovery-service  # Name registered in the Config Server

eureka:
  instance:
    hostname: localhost  # Hostname for Eureka display in the dashboard

  client:
    register-with-eureka: false  # This app is the Eureka server itself
    fetch-registry: false        # It doesn’t need to fetch registry entries
    service-url:
      # Other services will use this URL to register
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
