# ===============================================================
# CONFIG SERVER (config-server)
# Centralized configuration service for all microservices
# ===============================================================

server:
  port: 9090  # Port where the Config Server runs (default is 8888)

spring:
  application:
    name: config-server  # The name of this service in the Spring Cloud ecosystem

  profiles:
    active: native  # "native" means config files are stored locally (not in Git)

  cloud:
    config:
      server:
        native:
          # Folder where configuration files for each microservice are stored
          # Example: /resources/configurations/product-service.yml
          search-locations: classpath:/configurations

## Eureka registration settings (optional)
## Config Server usually does not need to register with Eureka
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    register-with-eureka: false
#    fetch-registry: false
